API/iLoveIbadah.Website/Controllers/BlogController.cs
using iLoveIbadah.Website.Contracts;
using iLoveIbadah.Website.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace iLoveIbadah.Website.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly ICommentService _commentService;

        public BlogController(IBlogService blogService, ICommentService commentService)
        {
            _blogService = blogService;
            _commentService = commentService;
        }

        // GET: BlogController
        public async Task<ActionResult> Index()
        {
            var model = await _blogService.GetAll();
            return View(model);
        }

        // GET: BlogController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var viewModel = new BlogWithCommentsVM
            {
                Blog = await _blogService.GetById(id),
                Comments = await _commentService.GetAll()
            };

            return View(viewModel);
        }

        // GET: BlogController/Create
        //public async Task<ActionResult> Create()
        //{
        //    return View();
        //}

        // POST: BlogController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: BlogController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View();
        }

        // POST: BlogController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BlogController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View();
        }

        // POST: BlogController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

API/iLoveIbadah.Website/Controllers/UserAccountController.cs
using iLoveIbadah.Website.Contracts;
using iLoveIbadah.Website.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace iLoveIbadah.Website.Controllers
{
    public class UserAccountController : Controller
    {
        private readonly IAuthenticationService _authenticationService;

        public UserAccountController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        public IActionResult Register()
        {
            return View();
        }

        // POST: UserAccountController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterVM registration)
        {
            if (ModelState.IsValid)
            {
                var returnUrl = Url.Content("~/");
                var isCreated = await _authenticationService.Register(registration);
                if (isCreated)
                {
                    return LocalRedirect(returnUrl);
                }
            }

            ModelState.AddModelError("", "Registration Attempt Failed. Please try again.");
            return View(registration);
        }

        public IActionResult Login(string returnUrl = null)
        {
            return View();
        }

        // POST: UserAccountController/Create
        [HttpPost]
        public async Task<IActionResult> Login(LoginVM login, string returnUrl)
        {
            returnUrl ??= Url.Content("~/");
            var isLoggedIn = await _authenticationService.Authenticate(login.Email, login.PasswordHash);
            if (isLoggedIn)
            {
                return LocalRedirect(returnUrl);
            }

            ModelState.AddModelError("", "Log in Attempt Failed. Please try again.");
            return View(login);
        }

        [HttpPost]
        public async Task<IActionResult> Logout(string returnUrl)
        {
            returnUrl ??= Url.Content("~/");
            await _authenticationService.Logout();
            return LocalRedirect(returnUrl);
        }
    }
}

API/iLoveIbadah.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iLoveIbadah</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/iLoveIbadah.Website.styles.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/utility.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
<div class="page">
<header class="header">
    <div class="wrapper header__content">
        <div class="brand">
            <span class="brand__logo">❤️</span>
            <p class="brand__name"><a href="/" class="brand__link">i Love Ibadah</a></p>
        </div>
        <nav class="nav">
            <ul class="nav__list">
                <li class="nav__item"><a class="nav__link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="nav__item"><a class="nav__link" asp-area="" asp-controller="Blog" asp-action="Index">Blogs</a></li>
                        @* <li class="nav__item"><a class="nav__link" asp-area="" asp-controller="UserAccount" asp-action="Login">Login</a></li> *@
                @if (User.Identity.IsAuthenticated)
                { 
                    <li class="nav__item"><a class="nav__link" asp-area="" asp-controller="UserAccount" asp-action="">@User.Identity.Name</a></li>
                    <li class="nav__item"><form class="nav__link" method="post" asp-controller="UserAccount" asp-action="Logout" asp-route-returnUrl="@Url.Action("Index", "Home")"><button type="submit" class="nav-link btn btn-link">Logout</button></form></li>
                }
                else
                {
                    <li class="nav__item"><a class="nav__link" asp-area="" asp-controller="UserAccount" asp-action="Login">Login</a></li>
                }
            </ul>
        </nav>
        <div class="social">
            <a href="#" class="social__link" title="Discord">
                <i class="fab fa-discord"></i>
            </a>
            <a href="#" class="social__link" title="X">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#" class="social__link" title="Github">
                <i class="fab fa-github"></i>
            </a>
        </div>
    </div>
</header>
<main class="main">
    @RenderBody()
</main>
<footer class="footer">
    <div class="wrapper footer__content">
        <div class="footer__top">
            <div class="footer__link-group">
                <h2 class="link-group__title">Product</h2>
                <ul class="link-group__list">
                    <li class="link-group__item"><a href="#" class="link-group__link">Download</a></li>
                            <li class="link-group__item"><a href="#" class="link-group__link">Github</a></li>
                            <li class="link-group__item"><a href="#" class="link-group__link">Changelog</a></li>
                </ul>
            </div>
            <div class="footer__link-group">
                <h2 class="link-group__title">Ressources</h2>
                <ul class="link-group__list">
                            <li class="link-group__item"><a class="link-group__link" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a></li>
                            <li class="link-group__item"><a href="#" class="link-group__link">Repository of Apps</a></li>
                            <li class="link-group__item"><a href="#" class="link-group__link">Newsletter</a></li>
                </ul>
            </div>
            <div class="footer__link-group">
                <h2 class="link-group__title">Myself</h2>
                <ul class="link-group__list">
                    <li class="link-group__item"><a href="#" class="link-group__link">About</a></li>
                </ul>
            </div>
            <div class="footer__link-group">
                <h2 class="link-group__title">Get in Touch </h2>
                <ul class="link-group__list">
                    <li class="link-group__item"><a href="#" class="link-group__link">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="footer__separator">
            <div class="separator__line"></div>
            <div class="brand">
                <span class="brand__logo">❤️</span>
                <p class="brand__name">ILoveIbadah</p>
            </div>
            <div class="separator__line"></div>
        </div>
        <div class="footer__bottom">
            <div class="footer__copyright">
                <p>&copy; 2025 iLoveIbadah. All rights reserved.</p>
            </div>
            <nav class="nav">
                <ul class="nav__list">
                    <li class="nav__item"><a href="#" class="nav__link">Terms and Conditions</a></li>
                    <li class="nav__item"><a href="#" class="nav__link">Privacy</a></li>
                </ul>
            </nav>
            <div class="social">
                <a href="#" class="social__link" title="Discord">
                    <i class="fab fa-discord"></i>
                </a>
                <a href="#" class="social__link" title="X">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#" class="social__link" title="Github">
                    <i class="fab fa-github"></i>
                </a>
            </div>
        </div>
    </div>
</footer>
    </div>
<!-- Default Scripts -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> <!-- Optional: If using Bootstrap -->
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>